# Generated by Django 6.0.3 on 2026-03-05 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('track_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('track_name', models.CharField(max_length=200)),
                ('artists', models.CharField(max_length=500)),
                ('album_name', models.CharField(max_length=200)),
                ('popularity', models.IntegerField()),
                ('duration_ms', models.IntegerField()),
                ('explicit', models.BooleanField()),
                ('danceability', models.FloatField()),
                ('energy', models.FloatField()),
                ('key', models.IntegerField()),
                ('loudness', models.FloatField()),
                ('mode', models.IntegerField()),
                ('speechiness', models.FloatField()),
                ('acousticness', models.FloatField()),
                ('instrumentalness', models.FloatField()),
                ('liveness', models.FloatField()),
                ('valence', models.FloatField()),
                ('tempo', models.FloatField()),
                ('time_signature', models.IntegerField()),
                ('track_genre', models.CharField(max_length=100)),
            ],
        ),
    ]
